version: "3.9"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ALLOWED_HOSTS=127.0.0.1,localhost
      - DEBUG=True     
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app    
